language: node_js
sudo: false

cache:
  directories:
    - node_modules

node_js:
  - "node"
  - "6"
  - "5"
  - "4"

install:
  - npm install
  - node -v
  - npm -v
  - npm run spec_setup && npm run test_build_cjs_run
